### PR TITLE
Specify which file decorator is requiring index from

### PR DESCRIPTION
**Pull request by lidawang**
This is the same as https://github.com/jasonslyvia/react-lazyload/pull/20 which got accidentally wiped when https://github.com/jasonslyvia/react-lazyload/pull/15 landed

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Oops, that's unfortunate.

**Comment by jasonslyvia** [comment]
I assume you will need a new version published?

**Comment by lidawang** [comment]
If you would be so kind!

**Comment by jasonslyvia** [comment]
Sure thing, `2.1.1` it is.

**Pull request merged**
