### PR TITLE
Use prop-types instead of React.PropTypes

### PR DESCRIPTION
**Pull request by MorisHarA**

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Great work, thanks! Can you confirm using a separate `prop-types` package will not break old React (14.x) builds?

**Comment by wilbert-abreu** [comment]
@jasonslyvia I can confirm this won't break React 14.x. This is a just a separate standalone package for handling react proptypes. Please merge this as soon as possible as it's causing warnings on my end. Thanks!

**Comment by jasonslyvia** [comment]
@wilbert-abreu Thanks for your confirmation.

**Comment by jasonslyvia** [comment]
please try `2.2.6`

**Comment by MorisHarA** [comment]
ok!

**Pull request merged**
