### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by SickSAMA**
Try to fix problems I mentioned in #33 and #17

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Awesome! But it seems breaking some tests?

**Comment by SickSAMA** [comment]
```
Firefox 31.0.0 (Linux 0.0.0) LazyLoad Basic setup should warn if custom placeholder has a largely varied `height` than `this.props.height` FAILED
```
I assume once the user provides placeholder, we don't care the height any more as it's never used.

**Comment by jasonslyvia** [comment]
Fair point, do you care removing related test?

**Comment by jasonslyvia** [comment]
Great, really appreciate your effort!

**Comment by SickSAMA** [comment]
Cheers! 😆

**Comment by jasonslyvia** [comment]
Do you need an immediate release regarding this change?

**Comment by SickSAMA** [comment]
Sure, thank you.

**Comment by jasonslyvia** [comment]
`2.1.4` it is.

**Pull request merged**
