### PR TITLE
Lazy Load working in overflow containers

### PR DESCRIPTION
**Pull request by mboperator**
### Description

I discovered that react-lazyloader doesn't check for visibility when the `scroll` event happens anywhere but the `window` (eg when the user scrolls inside of a div with `overflow-y`) This PR checks visibility on `wheel` events instead of on `scroll`, fixing the issue.

### Notable Changes
Removes scroll prop
Default behavior is use wheel, or fall back to mousewheel

### CODE REVIEW

**Comment by mboperator** [comment]
Not sure if you want a `wheel` prop instead. If we choose that route, should one take precedence over the other (eg: if `wheel===true` don't attach a scroll listener) ? Let me know.

**Comment by jasonslyvia** [comment]
Thanks @mboperator , I do miss the `overflow` situation. But as far as I know, `wheel` event is not supported on IE 8, so an option would be better.

**Comment by mboperator** [comment]
How about [this?](https://github.com/jasonslyvia/react-lazyload/pull/2/files#diff-1fdf421c05c1140f6d71444ea2b27638R99)

I opted to check for event support and removed the scroll prop altogether.

**Comment by jasonslyvia** [comment]
Seems good, but can you remove `scroll` unbinding in `componentWillUnmount`? 
https://github.com/mboperator/react-lazyload/blob/d90801ab8eb5baac1038d9ccc725f074c92239c8/src/index.js#L131

By the way, a squash of your commits would be much appreciated!

**Comment by mboperator** [comment]
Alright, commits squashed and all the events *should* be cleaned up on `componentWillUnmount`

**Comment by jasonslyvia** [comment]
Great job @mboperator , I'll publish a new version later for this feature.

**Comment by mboperator** [comment]
Awesome. Thanks @jasonslyvia :+1:

**Comment by jasonslyvia** [comment]
v1.1.0 published

**Comment by jasonslyvia** [comment]
However I'm considering another situation maybe `wheel` event may break, I'll add a demo later.

**Comment by jasonslyvia** [comment]
Demo added in #3

**Pull request merged**
