### PR TITLE
fixes #168 allow for custom scroll container

### LINKED ISSUE #168: can we custom the container?
As the title said ,  the we use the `transform` Instead of `overflow:scroll` to make div scroll in the old project , and this too complex to refactor. 

therefore we try to find a way to pass a `id` or DOM node in to custom the scroll container ,Does this feature can be support?

### PR DESCRIPTION
**Pull request by maikelmclauflin**
basic premise is to pass an id which can be queried for when the element mounts

### CODE REVIEW

**Comment by jasonslyvia** [comment]
excellent work! I believe it's ready to merge.

**Comment by mmclau14** [comment]
@jasonslyvia just wondering when this will be merged in

**Comment by steverob** [comment]
Can this be merged in please @jasonslyvia? :) Thanks!

**Comment by GonchuB** [comment]
This would make a great addition. Please consider merging this, as it adds a lot of flexibility and broadens the usage

**Comment by borisrorsvort** [comment]
@maikelmclauflin Exactly what I need. Would you add some doc in the readme as well?

**Comment by borisrorsvort** [comment]
@jasonslyvia Can this be merged yet? 😃

**Comment by daphnak** [comment]
@jasonslyvia this change is exactly what we need in a project I'm working on, it would be great it you could merge it or provide feedback on any problems with the PR.

**Comment by BloodShura** [comment]
So.....?

**Comment by maikelmclauflin** [comment]
Good point about the docs @borisrorsvort

**Comment by maikelmclauflin** [comment]
If he doesn't merge by the weekend, i'll just create a new npm package

**Comment by ameerthehacker** [comment]
@jasonslyvia sorry for the inconvenience @jasonslyvia no more maintains this repo, I maintain it and i will merge your PR before the weekend!.

**Comment by maikelmclauflin** [comment]
fixes #168

**Comment by ameerthehacker** [comment]
Thanks for the contribution @maikelmclauflin

**Comment by jasonslyvia** [comment]
I'm afraid I don't even have the environment ready for releasing this project, I've added you as a npm package maintainer, could you help release this package instead? @ameerthehacker

**Comment by jasonslyvia** [comment]
btw, if you are interested in taking ownership of this project, I'll be willing to hand it out.

**Comment by ameerthehacker** [comment]
@jasonslyvia Sure I would be more than happy to take ownership of this project!

**Comment by jasonslyvia** [comment]
hi @ameerthehacker , i'm sorry that after a discussion with my workmates we reached a conclusion that many of our business project rely on react-lazyload, and they feel like there is necessity to keep this project under control, so i believe i can no longer transfer this project to you, but you're always welcomed to be a maintainer. sorry again.

**Comment by ameerthehacker** [comment]
Hi @jasonslyvia It is completely understandable and I'm always happy to be of a maintainer!

**Comment by jasonslyvia** [comment]
and just a fyi, this project has been transferred to one of my colleagues, hope you guys get along well :)

**Comment by ameerthehacker** [comment]
Sure @jasonslyvia looking forward for it!

**Pull request merged**
