### PR TITLE
Fix IE getBoundingClientRect bug and upgrade packages

### PR DESCRIPTION
**Pull request by wub**

### CODE REVIEW

**Comment by wub** [comment]
Not sure what happened with the examples bundle - should that be compiled with a prod flag?

**Comment by jasonslyvia** [comment]
Oh, please just left out all the compiled code, so we can have a better diff.

**Comment by wub** [comment]
@jasonslyvia There you go, is that all of it?

**Comment by jasonslyvia** [comment]
Cool, seems you helped to fix a bunch of linting issue too. Really appreciate it! I guess we're good to go.

**Pull request merged**
