### PR TITLE
Adding lazyload for horizontal scrolling

### PR DESCRIPTION
**Pull request by ankitladhania**
The title says it all.

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Thanks for your contribution! 

It'd be nice if you leave out the changes in `lib/` so we can have a clear diff,  btw adding tests for this new feature would be much appreciated.

**Comment by ankitladhania** [comment]
OK. will make the changes and send the PR.

**Comment by ankitladhania** [comment]
@jasonslyvia please review the PR

**Comment by 0x80** [comment]
@jasonslyvia This is old. Why hasn't this been merged or closed yet?

**Comment by Redmega** [comment]
@0x80 Probably because code coverage check failed due to @ankitladhania not adding those tests...

**Comment by jasonslyvia** [comment]
Actually this should be closed since it's a relatively old PR before a bunch of refactoring, horizontal lazy load support will be added in 3.0.0 officially. Thanks again for all the efforts 😉

**Pull request closed without merging**
