### PR TITLE
React 16 peer dependencies

### PR DESCRIPTION
**Pull request by ulisesbocchio**

### CODE REVIEW

**Comment by jasonslyvia** [comment]
Hi @ulisesbocchio , thanks for your contribution. As early mentioned in #125 , `react-layzload` seems broken with React 16 and a refactor is on the way. I will keep this MR open till the refactor is done.

**Comment by jasonslyvia** [comment]
Based on the discussion in #126 , I believe it's safe to merge this PR.  Before merging, I'd like to investigate why CI failed.

**Comment by jasonslyvia** [comment]
closed for implemented in another commit, thanks for your PR anyway.

**Comment by ulisesbocchio** [comment]
yeah, no worries, thanks for getting the changes in somehow!

**Pull request closed without merging**
